import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/admin/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "BeaPetShopAdmin",
    description: "Generated by create next app",
    icons: "https://webadmin.beeart.vn/upload/image/20220629/6379211571097799404175786.jpg",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="admin flex">
                    <div className="admin__sidebar w-1/5 p-5">
                        <Sidebar />
                    </div>
                    <div className="admin__content">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
