import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/admin/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "BeaPetShopAdmin",
    description: "Generated by create next app",
    icons: "/images/Beapet.png",
};

export default function AdminLoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="  bg-blue-50">
            <body className={inter.className}>
                <div className="admin__content border w-1/3 m-auto mt-10">
                    {children}
                </div>
            </body>
        </html>
    );
}
